language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libc6-dev-i386
      - gcc-multilib
      - g++-multilib

before_install:
  # Fetch source sdk
  - git clone --depth=1 https://github.com/ValveSoftware/source-sdk-2013.git

script:
  - cmake . -DSOURCE_SDK_DIR=source-sdk-2013/mp/src
  - make all install
